name: anna kushnerova test 2
favicon: null
layout_spectrum: 0.8301206990145147
typography_spectrum: 0.11466516251675785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4497562062460929
  lightness: 0.0746702894102782
  saturation: 0.26617404562421143
  rhythmicContrast: 0.8683514886070043
purpose: []
